# -*- coding: utf-8 -*-
"""Assignment5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbfS5YOTSOhirACt_CgB4B5o0ba8eA87
"""

# RNN text generation using temperature based sampling

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

# Dataset

text = "The beautiful girl whom I met last time is very intelligent also"

# Unique characters and mapping
chars = sorted(list(set(text)))
char_to_index = {char: i for i, char in enumerate(chars)}
index_to_char = {i: char for i, char in enumerate(chars)}


# Prepare Sequences


seq_length = 5  # Length of input sequences
sequences = []
labels = []

for i in range(len(text) - seq_length):
    seq = text[i:i + seq_length]
    label = text[i + seq_length]
    sequences.append([char_to_index[char] for char in seq])
    labels.append(char_to_index[label])

X = np.array(sequences)
y = np.array(labels)

# One-hot encoding
X_one_hot = tf.one_hot(X, len(chars))
y_one_hot = tf.one_hot(y, len(chars))


# Build RNN Model


hidden_units = 50  # Number of RNN units

model = Sequential()
model.add(SimpleRNN(hidden_units, input_shape=(seq_length, len(chars)), activation='relu'))
model.add(Dense(len(chars), activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


# Train Model


model.fit(X_one_hot, y_one_hot, epochs=100, verbose=1)


# Text Generation with Temperature Sampling

def sample_with_temperature(preds, temperature=1.0):
    """
    Picks the next character index based on predicted probabilities and temperature.
    Higher temperature -> more random, lower -> more deterministic.
    """
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds + 1e-8) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)

start_seq = "The handsome boy whom I met "
generated_text = start_seq
text_len = 50  # Number of characters to generate
temperature = 0.8  # Adjust 0.5 - 1.0 for creativity

for i in range(text_len):
    x = np.array([[char_to_index[char] for char in generated_text[-seq_length:]]])
    x_one_hot = tf.one_hot(x, len(chars))
    prediction = model.predict(x_one_hot, verbose=0)[0]
    next_index = sample_with_temperature(prediction, temperature)
    next_char = index_to_char[next_index]
    generated_text += next_char

print("Generated Text:")
print(generated_text)