# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2ZDDLS-n3RQgNlhf4hFC4_2OfocwDvj
"""

# Q-Learning on Graph Environment


import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import random

# Graph Definition
edges = [
    (0, 1), (1, 5), (5, 6), (5, 4), (1, 2),
    (1, 3), (9, 10), (2, 4), (0, 6), (6, 7),
    (8, 9), (7, 8), (1, 7), (3, 9)
]

goal = 10
MATRIX_SIZE = 11

G = nx.Graph()
G.add_edges_from(edges)

plt.figure(figsize=(6, 6))
nx.draw(G, with_labels=True, node_color='lightblue')
plt.title("Environment Graph")
plt.show()

# Reward Matrix
R = np.matrix(np.ones((MATRIX_SIZE, MATRIX_SIZE))) * -1

for edge in edges:
    if edge[1] == goal:
        R[edge] = 100
    else:
        R[edge] = 0

    if edge[0] == goal:
        R[edge[::-1]] = 100
    else:
        R[edge[::-1]] = 0

R[goal, goal] = 100


# Q-Learning Setup
Q = np.matrix(np.zeros((MATRIX_SIZE, MATRIX_SIZE)))
gamma = 0.75
episodes = 1000

# Helper Functions
def available_actions(state):
    return np.where(R[state] >= 0)[1]

def choose_action(actions):
    return random.choice(actions)

def update_q(state, action):
    max_q = np.max(Q[action])
    Q[state, action] = R[state, action] + gamma * max_q
    return np.sum(Q / np.max(Q) * 100) if np.max(Q) > 0 else 0

# Training
scores = []

for _ in range(episodes):
    state = random.randint(0, MATRIX_SIZE - 1)
    actions = available_actions(state)
    action = choose_action(actions)
    score = update_q(state, action)
    scores.append(score)

# Testing Optimal Path
current_state = 0
path = [current_state]

while current_state != goal:
    next_state = np.where(Q[current_state] == np.max(Q[current_state]))[1]
    next_state = int(random.choice(next_state))
    path.append(next_state)
    current_state = next_state

print("Most Efficient Path:")
print(path)

# Training Reward Plot
plt.plot(scores)
plt.xlabel("Iterations")
plt.ylabel("Reward")
plt.title("Q-Learning Training Progress")
plt.show()


# Environment Awareness Extension
police = [2, 4, 5]
drug_traces = [3, 8, 9]

env_police = np.zeros((MATRIX_SIZE, MATRIX_SIZE))
env_drugs = np.zeros((MATRIX_SIZE, MATRIX_SIZE))

def sense_environment(action):
    found = []
    if action in police:
        found.append('p')
    if action in drug_traces:
        found.append('d')
    return found

def update_q_env(state, action):
    max_q = np.max(Q[action])
    Q[state, action] = R[state, action] + gamma * max_q

    env = sense_environment(action)
    if 'p' in env:
        env_police[state, action] += 1
    if 'd' in env:
        env_drugs[state, action] += 1

# Environment-aware training
scores_env = []

for _ in range(episodes):
    state = random.randint(0, MATRIX_SIZE - 1)
    actions = available_actions(state)
    action = choose_action(actions)
    update_q_env(state, action)
    scores_env.append(np.sum(Q))

plt.plot(scores_env)
plt.xlabel("Iterations")
plt.ylabel("Reward")
plt.title("Environment-Aware Q-Learning")
plt.show()

print("Police Matrix:\n", env_police)
print("\nDrug Trace Matrix:\n", env_drugs)
