# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6pM9jWuXKGLA0Jjv9CfutdJmJmE7Z9T
"""

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization

class AlexNet(Sequential):
    """
    Implementation of AlexNet using Keras Sequential API.

    Args:
        input_shape (tuple): Shape of input images, e.g., (224, 224, 3)
        num_classes (int): Number of output classes
    """
    def __init__(self, input_shape, num_classes):
        super(AlexNet, self).__init__()


        # Feature Extraction Layers


        # 1st Convolutional Layer
        self.add(Conv2D(filters=96, kernel_size=(11, 11), strides=4, padding='valid', activation='relu', input_shape=input_shape))
        self.add(MaxPooling2D(pool_size=(3, 3), strides=2, padding='valid'))
        self.add(BatchNormalization())

        # 2nd Convolutional Layer
        self.add(Conv2D(filters=256, kernel_size=(5, 5), strides=1, padding='same', activation='relu'))
        self.add(MaxPooling2D(pool_size=(3, 3), strides=2, padding='valid'))
        self.add(BatchNormalization())

        # 3rd, 4th, 5th Convolutional Layers
        self.add(Conv2D(filters=384, kernel_size=(3, 3), strides=1, padding='same', activation='relu'))
        self.add(Conv2D(filters=384, kernel_size=(3, 3), strides=1, padding='same', activation='relu'))
        self.add(Conv2D(filters=256, kernel_size=(3, 3), strides=1, padding='same', activation='relu'))
        self.add(MaxPooling2D(pool_size=(3, 3), strides=2, padding='valid'))
        self.add(BatchNormalization())


        # Classification Layers

        self.add(Flatten())
        self.add(Dense(4096, activation='relu'))
        self.add(Dropout(0.5))
        self.add(Dense(4096, activation='relu'))
        self.add(Dropout(0.5))
        self.add(Dense(num_classes, activation='softmax'))



# Example Usage
if __name__ == "__main__":
    input_shape = (224, 224, 3)  # Standard ImageNet size
    num_classes = 1000            # Number of classes
    model = AlexNet(input_shape, num_classes)
    model.summary()
