# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmY7HP3Nt02VP9eVPRkey7gWQnBBhg_-
"""

CNN based Cat vs Dog Classification


import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras import layers, models
from tensorflow.keras.optimizers import RMSprop


# Load Dataset using TFDS
(ds_train, ds_val), ds_info = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:]'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)

IMG_SIZE = 150
BATCH_SIZE = 32

def preprocess(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = image / 255.0
    return image, label

ds_train = ds_train.map(preprocess).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
ds_val = ds_val.map(preprocess).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)


# CNN Model Definition

model = models.Sequential([
    layers.Conv2D(16, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.summary()

# Model Compilation

model.compile(
    optimizer=RMSprop(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Model Training

history = model.fit(
    ds_train,
    epochs=20,
    validation_data=ds_val,
    verbose=2
)

# Accuracy & Loss Graphs

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(acc))

plt.figure()
plt.plot(epochs, acc)
plt.plot(epochs, val_acc)
plt.title("Training and Validation Accuracy")
plt.legend(["Train", "Validation"])
plt.show()

plt.figure()
plt.plot(epochs, loss)
plt.plot(epochs, val_loss)
plt.title("Training and Validation Loss")
plt.legend(["Train", "Validation"])
plt.show()


# Single Image Prediction
for image, label in ds_val.take(1):
    sample = image[0]
    sample = tf.expand_dims(sample, axis=0)

prediction = model.predict(sample)

print("Prediction:", "Dog" if prediction[0] > 0.5 else "Cat")
